<?php

namespace App\Tests\Unit\Wallet;

use App\Services\Wallet\FetchStatisticHandlers\FetchStatisticHandlerInterface;
use App\Services\Wallet\WalletService;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class WalletServiceTest extends TestCase
{

    /** @var EntityManagerInterface|MockObject */
    private $entityMangerMock;

    /** @var EntityManagerInterface|MockObject */
    private $validatorMock;

    /** @var EntityManagerInterface|MockObject */
    private $fetchStatisticHandler;

    /** @var EntityManagerInterface|MockObject */
    private $logger;

    protected function setUp(): void
    {
        $this->entityMangerMock = $this->createMock(EntityManagerInterface::class);
        $this->validatorMock = $this->createMock(ValidatorInterface::class);
        $this->fetchStatisticHandler = $this->createMock(FetchStatisticHandlerInterface::class);
        $this->logger = $this->createMock(LoggerInterface::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testNewInstance()
    {
        $walletService = new WalletService(
            $this->entityMangerMock,
            $this->validatorMock,
            $this->fetchStatisticHandler,
            $this->logger
        );
        $this->assertInstanceOf(WalletService::class, $walletService);

    }
}
